<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ApplicationIcon>Resources\Icons\icon.ico</ApplicationIcon>
    <StartupObject>AutoClicker.App</StartupObject>
    <PackageProjectUrl>https://github.com/BreezeDelegate/AutoClicker</PackageProjectUrl>
    <RepositoryUrl>https://github.com/BreezeDelegate/AutoClicker</RepositoryUrl>
    <Version>4.0.0-bd.1</Version>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <FileVersion>4.0.0.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Copyright>Copyright © 2024 oriash93 contributors; fork modifications © 2026 BreezeDelegate</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Resources\keyMappings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Icons\settings.ico" />
    <Resource Include="Resources\Icons\about.ico" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Icons\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Resources\Icons\location-crosshairs-solid.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Resources\Icons\icon_running.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.1">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../AutoClicker.Core/AutoClicker.Core.csproj" />
  </ItemGroup>
</Project>
